## CONFIGURATION FILE FOR make
## NEED TO BE CONFIGURED

# path to the c++-compiler executable
CC            = /usr/bin/g++     

# path to the directory containing the CXI header files
# location on installation CD: Software/Linux/<platform>/Crypto_APIs/CXI/include  
INC_DIR_CXI   = ../../../include

# path to the directory containing the CXI library
# location on installation CD: Software/Linux/<platform>/Crypto_APIs/CXI/lib
LIB_PATH      = ../../../lib
